### ISSUE TITLE
Timetable Phase 2.1

### ISSUE THREAD

**Issue by yookoala** [404busters/hkoscon-2017#107]
Improve UX on the current React table

* [ ] General UX
  * [x] Make everything in the table clickable.
  * [ ] Provide venue information for all sessions (minimap).
  * [x] On click, show topic details in modal box instead of another page.
* [ ] Topic Filter
  * [ ] Add tags to each topic (@yookoala)
  * [ ] Display topic tag on table and topic page.
  * [ ] Add topic filter.
* [ ] Responsive UX
  * [x] In small screen, have wrapper contain the table. Only content of table scroll horizontally. Not the whole body.
  * [ ] Make the time column sticky.

**Comment by yookoala** [comment]
Can also reference #21

**Comment by railsstudent** [comment]
Can I try "On click, show topic details in modal box instead of another page."?

**Comment by tonyhhyip** [comment]
For "Provide venue information for all sessions (minimap)", can refer to #105

**Comment by tonyhhyip** [comment]
For modal box, currently idea:
Render one modal box and pass the control methods with React Context
http://materializecss.com/modals.html
https://facebook.github.io/react/docs/context.html

**Comment by yookoala** [comment]
@railsstudent Sure. Please help yourself :-)

**Comment by yookoala** [comment]
About "make everything in the table clickable", that includes lunch, opening and non-topic sessions.

**Comment by railsstudent** [comment]
What is requirement of minimap? Display map on venue page on a new modal dialog?
