### ISSUE TITLE
Collect speaker slides

### ISSUE THREAD

**Issue by railsstudent** [404busters/hkoscon-2017#182]
Karl Lam
https://github.com/karlvlam/hkosc2017-demo

Amanda Lam:
https://docs.google.com/presentation/d/16pf0BiPmG6ZAvV2WYEiAhkXSidefYTFl9AMyswyHhgY/edit#slide=id.p

Cyrus Wong:
https://www.linkedin.com/pulse/aws-cloud-lab-one-more-real-educational-use-case-part-wong-1

Rick Mak:
https://go-talks.appspot.com/github.com/oursky/slides/zmq-multiplex.slide#1

**Comment by tonyhhyip** [comment]
Ryusuke Kajiyama
https://www.slideshare.net/IvanMa/whats-new-in-mysql-80-hkosc-2017
BlueBat
https://speakerdeck.com/bluebat

**Comment by tonyhhyip** [comment]
Dietrich Ayala
https://autonome.github.io/elephant/public/hkoscon-2017.html
Ivan Ma
https://www.slideshare.net/IvanMa/mysql-innodb-cluster-and-mysql-group-replication-hkosc-2017
D. Vigneshwer
http://dvigneshwer.github.io/files/AI_Rust.pdf
Gary Kwong
https://nth10sd.github.io/js-fuzzing-in-mozilla/

**Comment by irvin** [comment]
Irvin Chen
https://www.slideshare.net/irvinfly/mozilla-community-space-taipei-status-report-201706

**Comment by tonyhhyip** [comment]
Rick Ma
https://go-talks.appspot.com/github.com/oursky/slides/zmq-multiplex.slide#1

**Comment by dvigneshwer** [comment]
Building AI units in Rust
http://dvigneshwer.github.io/files/AI_Rust.pdf

**Comment by tonyhhyip** [comment]
Hayden Chung
http://submariner-maria-40063.bitballoon.com/

**Comment by chrischeungnf** [comment]
Chris Cheung
[https://github.com/chrischeungnf/tegaki-traditional-chinese-local/blob/master/HKOSCon17present.pdf](https://github.com/chrischeungnf/tegaki-traditional-chinese-local/blob/master/HKOSCon17present.pdf)

**Comment by railsstudent** [comment]
Daniel:
https://www.youtube.com/watch?v=x8eAmnBFfEk&feature=youtu.be
https://github.com/theosp/why-bash-talk

If you got Meteor installed on your machine, all you need to do is to clone and run $ meteor in the cloned folder
