### ISSUE TITLE
Schedule not working for browser don't support fetch()

### ISSUE THREAD

**Issue by irvin** [404busters/hkoscon-2017#183]
Hi, I found that Safari don't support service worker fetch() before iOS 10.3, so the schedule page is empty on those system and console will report following errors.  
![photo6129846689029269439](https://user-images.githubusercontent.com/165936/27066362-14db8110-5036-11e7-8d66-300a0661985e.jpg)

You can reproduce the error on iOS simulator with firmware before 10.2, I also believe this will happened on other browser too, http://caniuse.com/#feat=fetch

You may tried to polypill this with this? https://github.com/github/fetch

**Comment by tonyhhyip** [comment]
Polyfill is already added
https://github.com/404busters/hkoscon-2017/commit/e1252375f0bcd2b520b859e74116fe2914e4b7d4#diff-97b4088e5a60b2df6ee0d21a66902786

**Comment by irvin** [comment]
weird, still not working. There must be some other problems...

**Comment by irvin** [comment]
<img width="1440" alt="2017-06-13 15 46 34" src="https://user-images.githubusercontent.com/165936/27071468-aecc559c-504f-11e7-823d-ff26115f843e.png">
No more error message but still not working.

**Comment by tonyhhyip** [comment]
It is working well on my Macbook Safari...

**Comment by irvin** [comment]
it was not working on IE, Android < 4.4.4, iOS < 10.2...
I can only verified that it still not working on iOS < 10.2 for now.

check caniuse > http://caniuse.com/#feat=fetch

**Comment by tonyhhyip** [comment]
Solved by replacing fetch with `axios` in PyCon website
