### ISSUE TITLE
Add manifest.json file

### ISSUE THREAD

**Issue by tonyhhyip** [404busters/hkoscon-2017#19]
Please refer to [https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json)

**Comment by railsstudent** [comment]
where do I put this file?

**Comment by railsstudent** [comment]
https://developer.chrome.com/extensions/manifest

**Comment by tonyhhyip** [comment]
Closed in #44
