### ISSUE TITLE
Display avartar in staff list

### ISSUE THREAD

**Issue by railsstudent** [404busters/hkoscon-2017#63]

**Comment by yookoala** [comment]
We need to have photos of our staffs first :-)

**Comment by tonyhhyip** [comment]
@yookoala I plan to use gravatar with fallback image ~~ok, I already collect some photos~~

**Comment by yookoala** [comment]
Not everyone has a gavatar. We can still try.

Also better ask around first. Not everyone prefer showing their face in our website. Some of them might want to stay mysterious (like 賭神[高進](https://zh.wikipedia.org/zh-hk/%E8%B3%AD%E7%A5%9E)).

**Comment by yookoala** [comment]
I last asked in the Team Lead channel, nobody was answering.

**Comment by tonyhhyip** [comment]
We will show those have confirmed to show, I have confirmed with some people

**Comment by tonyhhyip** [comment]
Closed by #66 and #70
