### ISSUE TITLE
Have the option to show name and company in staff list

### ISSUE THREAD

**Issue by railsstudent** [404busters/hkoscon-2017#76]
If company name is provided, I can promote my company in my volunteer effort.

The point to volunteer in these events is to talk to talents and attract talents to join in the future.

**Comment by yookoala** [comment]
I think that could be a problem for the sponsors. Let's raise this on the slack channels.

**Comment by tonyhhyip** [comment]
No a good idea

**Comment by railsstudent** [comment]
Whatever .

**Comment by yookoala** [comment]
After discussion in the team lead channel, it is considered not an appropriate change.
