### ISSUE TITLE
Add theme color and browser outlook

### ISSUE THREAD

**Issue by tonyhhyip** [404busters/hkoscon-2017#82]
Refers to https://developers.google.com/web/fundamentals/design-and-ui/browser-customization/

**Comment by tonyhhyip** [comment]
https://developers.google.com/web/updates/2014/11/Support-for-theme-color-in-Chrome-39-for-Android
Starting from chrome 39, theme colour and icon is provided for tabs. Please add the deep blue as theme colour and icon (https://hkoscon.org/logo.png) in meta tag

**Comment by railsstudent** [comment]
Got it. Will do it tonight.

**Comment by tonyhhyip** [comment]
Closed with #89 and #86
